theme: jekyll-theme-minimal
title: Password Guardian
url: "https://guardians-of-the-software-galaxy.github.io/password-guardian.github.io/"
# Edit next line so that baseurl is "" if your repo is <username>.github.io
baseurl: ""