title: Password Guardian
# Edit next line, replacing 'techfolios' with your github username
url: "https://password-guardian.github.io"
# Edit next line so that baseurl is "" if your repo is <username>.github.io
baseurl: ""
